CREATE TABLE R1(
    A INTEGER,
    B1 INTEGER,
    C1 INTEGER,
    D1 INTEGER,
    E1 INTEGER,
    F1 INTEGER,
    G1 INTEGER,
    H1 INTEGER,
    I1 INTEGER,
    JI INTEGER
);

CREATE TABLE R2(
    A INTEGER,
    B2 INTEGER,
    C2 INTEGER,
    D2 INTEGER,
    E2 INTEGER,
    F2 INTEGER,
    G2 INTEGER,
    H2 INTEGER,
    I2 INTEGER,
    J2 INTEGER
);

CREATE TABLE R3(
    A INTEGER,
    B3 INTEGER,
    C3 INTEGER,
    D3 INTEGER,
    E3 INTEGER,
    F3 INTEGER,
    G3 INTEGER,
    H3 INTEGER,
    I3 INTEGER,
    J3 INTEGER
);

CREATE TABLE R4(
    A INTEGER,
    B4 INTEGER,
    C4 INTEGER,
    D4 INTEGER,
    E4 INTEGER,
    F4 INTEGER,
    G4 INTEGER,
    H4 INTEGER,
    I4 INTEGER,
    J4 INTEGER
);

CREATE TABLE R5(
    A INTEGER,
    B5 INTEGER,
    C5 INTEGER,
    D5 INTEGER,
    E5 INTEGER,
    F5 INTEGER,
    G5 INTEGER,
    H5 INTEGER,
    I5 INTEGER,
    J5 INTEGER
);

CREATE TABLE R6(
    A INTEGER,
    B6 INTEGER,
    C6 INTEGER,
    D6 INTEGER,
    E6 INTEGER,
    F6 INTEGER,
    G6 INTEGER,
    H6 INTEGER,
    I6 INTEGER,
    J6 INTEGER
);

CREATE TABLE R7(
    A INTEGER,
    B7 INTEGER,
    C7 INTEGER,
    D7 INTEGER,
    E7 INTEGER,
    F7 INTEGER,
    G7 INTEGER,
    H7 INTEGER,
    I7 INTEGER,
    J7 INTEGER
);